// <auto-generated />
using System;
using ClothesSaleManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothesSaleManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ClothesSaleManagementContext))]
    partial class ClothesSaleManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClothesSaleManagement.Domain.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Bill", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc0b414e-9eab-4527-b3fb-6efba68748ff"),
                            CreatedDate = new DateTime(2023, 8, 2, 17, 57, 17, 109, DateTimeKind.Local).AddTicks(3888),
                            CustomerName = "Lê Xuân Minh Chiến",
                            PhoneNumber = "0123123423",
                            Status = 1,
                            TotalPayment = 20000m
                        },
                        new
                        {
                            Id = new Guid("fe382f6d-a7fc-4f6e-9843-239f0d6284bf"),
                            CreatedDate = new DateTime(2023, 8, 2, 17, 57, 17, 109, DateTimeKind.Local).AddTicks(3901),
                            CustomerName = "Nguyễn Ngọc Diệp ",
                            PhoneNumber = "0132312342",
                            Status = 1,
                            TotalPayment = 100000m
                        },
                        new
                        {
                            Id = new Guid("b2262bf3-7a66-465f-88ca-230c757e6287"),
                            CreatedDate = new DateTime(2023, 8, 2, 17, 57, 17, 109, DateTimeKind.Local).AddTicks(3904),
                            CustomerName = "Nguyễn Ngọc Diệp",
                            PhoneNumber = "0132312342",
                            Status = 1,
                            TotalPayment = 200000m
                        });
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.BillDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ProductId");

                    b.ToTable("BillDetail", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8d733f0-6745-4be3-9072-39c4a52c803f"),
                            BillId = new Guid("cc0b414e-9eab-4527-b3fb-6efba68748ff"),
                            Price = 20000m,
                            ProductId = new Guid("c1abc698-7149-49e2-b67f-e50f09d8e0c0"),
                            Quantity = 1,
                            TotalMoney = 20000m
                        },
                        new
                        {
                            Id = new Guid("18f91fdb-39d3-4fcc-b8ca-896ef777d840"),
                            BillId = new Guid("fe382f6d-a7fc-4f6e-9843-239f0d6284bf"),
                            Price = 25000m,
                            ProductId = new Guid("ed884572-cdeb-46ad-a2b2-12297e9fd32a"),
                            Quantity = 2,
                            TotalMoney = 50000m
                        },
                        new
                        {
                            Id = new Guid("374bf0a6-039f-42a9-b232-e4c90998b4c2"),
                            BillId = new Guid("fe382f6d-a7fc-4f6e-9843-239f0d6284bf"),
                            Price = 10000m,
                            ProductId = new Guid("ed884572-cdeb-46ad-a2b2-12297e9fd32a"),
                            Quantity = 5,
                            TotalMoney = 50000m
                        },
                        new
                        {
                            Id = new Guid("574ee723-685c-4bfa-8235-44d085434b74"),
                            BillId = new Guid("b2262bf3-7a66-465f-88ca-230c757e6287"),
                            Price = 100000m,
                            ProductId = new Guid("66bdf5a9-58b0-42b8-8508-c95e2518582a"),
                            Quantity = 2,
                            TotalMoney = 200000m
                        });
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.CartDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartDetail", (string)null);
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe702e57-9cb1-4c9f-8157-b0d19b1a7c03"),
                            Name = "Top tank",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("dcb0eb8d-d2a7-4849-bb94-47049486567f"),
                            Name = "T-Shirt",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b4a85960-d2b0-45b6-8fed-015fe61b5016"),
                            Name = "Áo phông",
                            Status = 0
                        });
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SizeId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1abc698-7149-49e2-b67f-e50f09d8e0c0"),
                            AvailableQuantity = 100,
                            CategoryId = new Guid("fe702e57-9cb1-4c9f-8157-b0d19b1a7c03"),
                            CostPrice = 50000m,
                            CreatedDate = new DateTime(2023, 8, 2, 17, 57, 17, 110, DateTimeKind.Local).AddTicks(1187),
                            Description = "Sang xịn mịn",
                            ImageUrl = "",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo phông chanh xả",
                            Price = 100000m,
                            SizeId = new Guid("f306c6f6-8a72-4c20-9031-2310cf8bf042"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ed884572-cdeb-46ad-a2b2-12297e9fd32a"),
                            AvailableQuantity = 100,
                            CategoryId = new Guid("dcb0eb8d-d2a7-4849-bb94-47049486567f"),
                            CostPrice = 20000m,
                            CreatedDate = new DateTime(2023, 8, 2, 17, 57, 17, 110, DateTimeKind.Local).AddTicks(1193),
                            Description = "Sang xịn mịn",
                            ImageUrl = "",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo top tank sẹc xi",
                            Price = 50000m,
                            SizeId = new Guid("af100821-2fd2-4d2d-a95e-04c772bceeb6"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("66bdf5a9-58b0-42b8-8508-c95e2518582a"),
                            AvailableQuantity = 100,
                            CategoryId = new Guid("dcb0eb8d-d2a7-4849-bb94-47049486567f"),
                            CostPrice = 20000m,
                            CreatedDate = new DateTime(2023, 8, 2, 17, 57, 17, 110, DateTimeKind.Local).AddTicks(1197),
                            Description = "Thoáng mát",
                            ImageUrl = "",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Áo T-shirt co dãn",
                            Price = 50000m,
                            SizeId = new Guid("af100821-2fd2-4d2d-a95e-04c772bceeb6"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Size", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f306c6f6-8a72-4c20-9031-2310cf8bf042"),
                            Name = "S",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2a765a9f-2dca-41d3-9570-e1ce39dc1f28"),
                            Name = "M",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("af100821-2fd2-4d2d-a95e-04c772bceeb6"),
                            Name = "L",
                            Status = 0
                        });
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.BillDetail", b =>
                {
                    b.HasOne("ClothesSaleManagement.Domain.Bill", "Bil")
                        .WithMany("BillDetails")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesSaleManagement.Domain.Product", "Product")
                        .WithMany("BillDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bil");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.CartDetail", b =>
                {
                    b.HasOne("ClothesSaleManagement.Domain.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesSaleManagement.Domain.Product", "Product")
                        .WithMany("CartDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.Product", b =>
                {
                    b.HasOne("ClothesSaleManagement.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClothesSaleManagement.Domain.Size", "Size")
                        .WithMany("Products")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.Bill", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.Product", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("ClothesSaleManagement.Domain.Size", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
